### ISSUE TITLE
Unclear error message when using unsupported position argument

### ISSUE THREAD

**Issue by pachacamac** [Flyer53/jsPanel4#112]
Accidentally used `position: 'center-center'` and the resulting error message threw me off quite a bit:
`jspanel.js:1112 Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': '-' is not a valid selector.`

Maybe there could be a clearer error message in such cases.

PS: Really awesome project though :)

**Comment by Flyer53** [comment]
@pachacamac 
Thanks for the info ... I'll see what I can do about that.
And thanks for the praise 😄

**Comment by Flyer53** [comment]
I'll probably just reset `"center-center"` to `"center"` internally before the position values are processed. So it's save to use and won't cause an error.

**Comment by pachacamac** [comment]
That would've helped in this case. Don't mind the strictness though. Maybe a check to see if the value is inside a list of acceptable values and if not throw a "invalid position attribute" error or so?

**Comment by Flyer53** [comment]
Ok, after looking into this a bit I came to the conclusion that there's not much to do about this. Why:
+ when unsupported values are used it's quite natural that something might go wrong and result in some kind of error msg
+ the position shorthand is a convenience. It would mean an awful lot of extra code even trying to filter out all possibly wrong values. And unfortunately most browsers support only a limited set of regex features (e.g. I had some neat options using a regex using a _negative lookbehind_ just to find out Firefox doesn't support it).
+ I personally think the docs are quite clear about what values are allowed

However, I'll try to improve things constantly ...

**Comment by pachacamac** [comment]
Fair enough. I thought you'd check this against a list of valid values anyways somewhere (sort of like [here](https://github.com/Flyer53/jsPanel4/blob/master/source/jspanel.js#L1303) or [here](https://github.com/Flyer53/jsPanel4/blob/master/source/jspanel.js#L1493-L1504) but I guess it's a bit more dynamic than that.

**Comment by Flyer53** [comment]
@pachacamac 
Since it's also possible to set `position.of` in the shorthand string it's really tricky to filter out what sub-string is intended for what position setting. There is almost an endless amount of possible combinations. So far I didn't find a better solution than the existing one. Better JavaScript support for regular expressions would help a lot ...

What happend in your example:
In the string `center-center` the first `center` was recognized as value for **my** and the second as value for **at** leaving the `-`. After filtering out values for **offsets** and **autoposition** the `-` still remains. And everything left over is seen as a selector string for `position.of`. Well, a single dash is not a valid selector string and thus you got the error.
