### ISSUE TITLE
Missing HTML5 type="button" causing HTTP submit form

### ISSUE THREAD

**Issue by afourmy** [Flyer53/jsPanel4#113]
Hello,

Whenever the panel is created from inside a form in the DOM (not unusual for a tooltip), clicking on the header buttons (close for example) will redirect to a blank "Bad Request" page because it doesn't have a `type="button"` attribute.

ref: https://stackoverflow.com/a/10836076
Example of a fix for the close button:
`...<button type="button" class="jsPanel-btn jsPanel-btn-close" aria-label="Close">').concat(this.icons.close...`

Thanks

**Comment by Flyer53** [comment]
Hi there,

Thanks for the info 😄  I'll look into ...

**Comment by Flyer53** [comment]
@afourmy 
I created a very simple demo file ([https://jspanel.de/docs/demos/test-form.html](https://jspanel.de/docs/demos/test-form.html)) to reproduce your issue but don't get any error msg or unexpected redirect. I was wondering anyhow because all handlers for the header controls have an `e.preventDefault()` in the code.

Although I'll add `type="button"` to the header controls with the next release anyhow I'd ask to to check whether there's something else in your code that might cause this behaviour.

Regards,
Stefan

**Comment by afourmy** [comment]
I did check but sorry, I haven't been able to reproduce it with your simple demo, nor have been able to determine what it is exactly that's triggering that behavior in my code... It's a large project with lots of javascript and css, and the html is for the most part generated front-end by javascript... Anyway, I haven't been able to identify the root cause, I can only inform you that not having `type="button"` leads to the form being submitted when you try to close the tooltip (the reason I get a bad request is because it's missing a CSRF token, but in a basic setup the page would simply reload), and adding `type="button"` fixes the issue.

Regards,

**Comment by Flyer53** [comment]
[v4.10.0-alpha](https://alpha.jspanel.de/downloads/jspanel-4.10.0-alpha.zip) includes the updated panel template adding `type="button"` to the controls.

**Comment by Flyer53** [comment]
Fixed with v4.10.0
