### ISSUE TITLE
QUESTION: If latest version is NOT based in jquery...

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel4#116]
Can jQuery slim still be used to control it?

or 

Does it only work with plain vanilla javascript?

Thanks

**Comment by Flyer53** [comment]
Hi Hugo,
Of course you can use jQuery and jsPanel in one project.
But what exactly do you mean with "control the panel with jQuery"?

If you mean calling a panel method on a jQuery object than you can do this by addressing the panel element inside the jQuery object.

Example:
Create a panel with a known id
```javascript
jsPanel.create({
  id: 'panel-1',
});
```
Get panel with jQuery and close it (as example)
```javascript
$('#panel-1')[0].close();
````
Remember that `$('#panel-1')` creates a jQuery object where index [0] points to the panel within.

Another example: get all panels and close them
```javascript
$('.jsPanel').each(function(index, panel){
  panel.close();
});
```

But you can not call a panel method directly on a jQuery object because the jsPanel script does not extend a jQuery object with anything.

Does that help you?

**Comment by Flyer53** [comment]
@inglesuniversal 
Hey Hugo,
Is there anything open on this issue? If not I'd ask you to close the issue. Otherwise let me know how I can help ....
Regards,
Stefan

**Comment by inglesuniversal** [comment]
I will close the issue, but before I want to thank you for being an amazing developer and a great fiendly tech coach.
