### ISSUE TITLE
[BUG] panel broken after resizing when smallified

### ISSUE THREAD

**Issue by afourmy** [Flyer53/jsPanel4#117]
Steps to reproduce:
- Open a jspanel
- Click on the button to reduce the size to the header ("smallify" I think is what you call it)

![bug](https://user-images.githubusercontent.com/16152622/75438019-7f3dba00-5957-11ea-949f-925ec49b13d9.PNG)

- Then resize the header to make it smaller, from the left or the right side. We see that the arrow of the smallify button will change its direction.
- Try to "unsmallify" the panel. It's kinda broken now

**Comment by Flyer53** [comment]
Ok, that's something I have to look at. Thanks for the report.

**Comment by Flyer53** [comment]
Fixed this issue in v4.10.0-alpha.

I would appreciate if you [donwload the current alpha](https://alpha.jspanel.de/downloads/jspanel-4.10.0-alpha.zip) and give it a try.

One glitch remains: when you smallify the panel and then "unsmallify" it with the mouse instead of using the smallify/unsmallify control you'll have to doubleclick the smallify control in order to properly smallify the panel again.

**Comment by Flyer53** [comment]
Fixed with v4.10.0

**Comment by afourmy** [comment]
I tried and I confirm that it is fixed. I also tried https://github.com/Flyer53/jsPanel4/issues/113 and it is fixed too with v4.10.0
Thanks !
