### ISSUE TITLE
jsPanel4 Example Question

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel4#119]
Based on the following code, I have two issues, how to auto-resize to 100% (minus 50px top header bar) an external URL on device rotate (landscape & portrait) and how do I remove the drag default icon:

I tried this:

```javascript

    jsPanel.create({
        theme: '#011842 filled',
        headerTitle: 'Coronavirus World Map | Powered by MyCloudVIP',
        headerLogo: '../favicon.png',
        dragit: 'disable',
        headerControls: {
            minimize: 'remove',
            maximize: 'remove',
            smallify: 'remove',
            close: 'remove'
        },
        contentSize: {
            width:  window.innerWidth,
            height: window.innerHeight - '50px'
        },
        onwindowresize: function(event, panel) {
        panel.reposition(panel.options.position);
        },
        contentOverflow: 'hidden',
        content: '<iframe src="https://external-domain.com" style="width: 100%; height: 100%;"></iframe>'
    });
```

Thanks

**Comment by Flyer53** [comment]
Hi Hugo,

If you are satified having a solution for mobile devices you can use the `orientationchange` event. Example code:
```javascript
var panel = jsPanel.create({
    theme: '#011842 filled',
    headerTitle: 'Coronavirus World Map | Powered by MyCloudVIP',
    // headerLogo: '../favicon.png',
    dragit: false,
    headerControls: 'none',
    setStatus: 'maximized',
    maximizedMargin: [50, 10, 10 ,10],
    contentOverflow: 'hidden',
    content: '<iframe src="../../img/071203/pano.html" style="width:100%; height:100%; border:none;"></iframe>',
    onwindowresize: function(event, panel) {
        panel.maximize();
    },
});

window.onorientationchange = function() {
    panel.maximize();
};
```
Some more explanations:
+ `dragit: 'disable'` does not work; use either `dragit: false` if you don't ever need to re-enable the dragit interaction for that panel, or otherwise `dragit: {disable: true}`
+ using the correct dragit config will take care of the drag cursor as well
+ the 50 pixel distance from top: Your code basically makes the panel as big as the window, so create the panel with a _maximized status_ (using option `setStatus`) and keep the top distance by using option `maximizedMargin` (for the demo I set a margin on all four sides)
+ to remove all controls use `headerControls: 'none'` (that's easier than setting each control separately). Are you sure you don't want to have a close button?

I created a simple demo with the code above you can check out: http://alpha.jspanel.de.localhost/docs/demos/test-hugo.html

Checked this only on my Galaxy Tab S3 and my Galaxy S10+ mobile phone since I don't have that much mobile devices ...

**Comment by Flyer53** [comment]
Hi Hugo,
You didn't respond to this issue for more than 6 weeks now.
I really would appreciate some feedback when I try to help.
Regards,
Stefan

**Comment by inglesuniversal** [comment]
picking up the topic...

**Comment by inglesuniversal** [comment]
Tested and worked flawlessly
