### ISSUE TITLE
are there any breaking changes between v4.5.0 and the latest?

### ISSUE THREAD

**Issue by inglesuniversal** [Flyer53/jsPanel4#123]
I am about to update my code and wish to know if there are things to consider

Stay safe!

Best regards

**Comment by Flyer53** [comment]
Hi Hugo,
v4.5.0 is more than a year old, so quite a few things happened since then. But I'm not aware of any changes that might break existing code. You just have to try. For details please refer to the [CHANGELOG](https://github.com/Flyer53/jsPanel4/blob/master/CHANGELOG.md)

Same to you Hugo ... stay healthy

Btw: You didn't respond to #119 for almost 4 weeks now??

**Comment by inglesuniversal** [comment]
Thanks
