### ISSUE TITLE
Close window with touch

### ISSUE THREAD

**Issue by Speuta** [Flyer53/jsPanel4#128]
On closing window with touch device, the event on the close button is propagated, and if there's another button below, it's clicked too.
Maybe a preventDefault or stopPropagation is missing on the touch event...

**Comment by Flyer53** [comment]
Don't worry about the repo ... I moved it to jsPanel 4 already.
Well I just tried your code and it doesn't change anything in my tests. Tried with an Galaxy Tab S3 with various browsers. And only browsers based on Chromium have this issue. Firefox works perfectly well concerning this issue. I'm a bit clueless right now ...

**Comment by Speuta** [comment]
Maybe it's the `pointerup`...

So the `preventDefault()` doesn't catch nothing because the button below is binded on `click` or on `pointerdown`, and so the close button is triggered after that...

Is there a reason that you have chosen `pointerup` ?

**Comment by Flyer53** [comment]
The good news first: I seem to have it fixed, although not in the way I prefered.

Yes, it has to do with the Pointer Event API. Either browser implementations are weird or I simply miss something very specific. I don't know. So far I couldn't find anything explaining why a button or link "underneath" a panel control gets triggered too.
To me it seemed natural to use the Pointer Event API where supported since you don't need to worry about Touch, Mouse, Pen or whatever and use Touch and Mouse only where Pointer Events are not supported. One goal always was to have a solution that works with Touch/Pen **AND** Mouse at the same time.

Ok, for testing I have a [version 4.11.0-alpha you can download](https://alpha.jspanel.de/downloads/jspanel-4.11.0-alpha.zip) that completely does without Pointer Events, only Touch and Mouse are used. I would appreciate if you gave it a try and let me know how it works out.
**Important note:** v4.11.0-alpha also includes completely recoded methods `jsPanel.ajax()` and `jsPanel.fetch()` and thus affecting options `contentAjax` and `contentFetch` possibly breaking existing code. So don't be surprised. The docs on [alpha.jspanel.de](https://alpha.jspanel.de/api.html#options/overview) should be up to date.

**Comment by Flyer53** [comment]
v4.11.0-beta does without using the Pointer Event API.
So for the time being this issue is fixed.
