### ISSUE TITLE
jsPanel display inside viewport

### ISSUE THREAD

**Issue by SeanBannister** [Flyer53/jsPanel4#129]
Thank you for this project it's extremely handy. 

Looking at [Tooltip example 4](https://jspanel.de/api.html#extensions/tooltip/example-4) the tooltip changes position if it's outside the viewport. But it's a little jaring for the user because it first displays one side and then switches to the other. I was wondering if there was an easy way to make it display on the correct side initially. I've considered writing some code that parses the values to [position](https://jspanel.de/api.html#options/position) when it's first initialized rather than updating the position, but I'm hoping there was a more robust solution as I imagine I might run into some interesting edge cases writing this code.

I currently have an implementation using jsPanel and [jQuery UI position](https://api.jqueryui.com/position/) (I use [this version](https://cdn.jsdelivr.net/npm/@rafael.baron/jquery-ui-position@1.12.1/jquery-ui.js) which strips out the rest of jQuery UI). It's positioning options are very similar to your own but it also provides an option called `collision` which can be set to flip in which case it flips the tooltip to the opposite side if it's outside the viewport. It'd be awesome if jsPanel had the same collision option in position.

The reason I'm moving away from jQuery UI position is I can't use the tooltip arrow of jsPanel when using it because there's no way to set it and I'm trying to move away from jQuery.

Was just looking for advice on how you think this should be implemented, tempted to add the feature to jsPanel but it's always daunting digging into big projects.

**Comment by Flyer53** [comment]
Hi Sean,
I was aware of that issue. But to be frank ... I never really cared about it very much. Nevertheless you're absolutely right. It's not ideal.

And I found a surprisingly easy solution, although it's more or less a hack. In order to check it out yourself you need to [download the latest v4.11.0-alpha](https://alpha.jspanel.de/downloads/jspanel-4.11.0-alpha.zip). It's not going to work with the 4.10.2 release. [Example 4](https://alpha.jspanel.de/api.html#extensions/tooltip/example-4) in the alpha docs is also updated. So you can check it there first.

**What did I do:**
Any panel you create starts with its `opacity` set to `0`. But the positioning function sets `opacity` to `1` as soon as the panel is positioned. I added a new option `opacity` that can be set to any valid value for css opacity. If this new option is set the positioning function will set opacity to this value at the end and not simply to `1`. So if you set this new option opacity to `"0"` (a zero must be in a string) then the panel remains "invisible" until you actively reset opacity which in example 4 is done in the callback checking whether the panel needs to be repositioned. Check out the sample code and you'll understand. In this example the tooltip is still positioned on top first, but it's not visible until its opacity is set after repositioning. Not very elegant ... but seems to work.

**Important note on v4.11.0-alpha.**
If you decide to try the 4.11.0-alpha you need to know that there is a potentially breaking change in `jsPanel.ajax()` and `jsPanel.fetch()` affecting options `contentAjax` and `contentFetch` as well. So if you use those options check out the alpha docs.

**One more note:**
I currently focus on rewriting the complete jsPanel website using tailwind.css instead of bootstrap and no jQuery either. To take a look at the preview go to [https://beta.jspanel.de/#home](https://beta.jspanel.de/#home). I would appriciate a little feedback 😏

**Comment by SeanBannister** [comment]
Thank you so much for your help with this, sorry for the late response just been spending some time moving my application over to tooltips from regular jsPanels.

I've improved upon your example in [this jsFiddle](https://jsfiddle.net/g5u0n7j3/) (its running 4.10 for ease of including the lib from CDN)  I though I'd leave it here in case it helps someone. Or if you thought it was worth including in the docs (its not pretty but it does the job). If a user wants to use `position: { my: 'left-top', at: 'left-bottom')` (jsPanel on the bottom right corner) the panel might display outside the right side of the viewport or the bottom. This code basically rotates the jsPanel around the outside of the element until it finds a location where its not outside the viewport 🙂

But I noticed an issue when doing this, the arrow turns into a dot, for example:
![image](https://user-images.githubusercontent.com/197231/84247363-567ab280-ab4b-11ea-825d-18aaac18d2b5.png)

Is this by design? I was expecting something like:
![image](https://user-images.githubusercontent.com/197231/84315670-58755d80-abad-11ea-90c2-1594d314e3fc.png)


I also think there might be a bug with `panel.overlaps('window').overlaps` I noticed it always equals `true`. You can check the console.log on [this jsFiddle](https://jsfiddle.net/g5u0n7j3/). 

I also noticed `panel.overlaps('window').bottom` and `top` seems to be incorrect, I thought this might be due to the boxshadow or header but neither seem to affect it. I see in [you example](https://alpha.jspanel.de/api.html#extensions/tooltip/example-4) you account for this with ` < 60`. Do you know what's causing this and would 60 be a consistent calculation?


Also the new docs look great, I love the design change it really modernized them. Looking forward to using them more!!! Thanks again for your help and for this library its saving me a heap of time on a personal project I'm working on.

**Comment by Flyer53** [comment]
My pleasure 😏 
+ the connector dot at the corner positions is by design. When tooltip and target corners already point at each other another arrow-like connector doesn't make sense to me. And I don't want to shift the tooltip in any direction.
+ the `< 60` value in the example is specific to this example. With a lower value the tooltip would be partly hidden by the Bootstrap top navbar which has a higher z-index. I updated the example to check against the navbar (don't ask why didn't do that from the beginning ...).
+ concerning a possible bug in `panel.overlaps()` I need to check that out. Did you check that in your website as well or just in the fiddle? Does the iframe the fiddle example code runs in has its own window object? Or do the iframe and the host page share the same window object?

Thanks a lot for your notes and the fiddle 😄 
Glad you like jsPanel ... and the new design of the doc pages.

**Comment by SeanBannister** [comment]
I did up a [quick demo](http://www.seanbannister.com/jspanel/) outside of jsFiddle showing the panel.overlaps() bug based on jsPanel 4.11.0-alpha. The bug certainly appears to be an issue. If you shrink the browser completely you'll notice overlaps displays false which is the opposite of what you'd expect.

In my last post I mentioned panel.overlaps('window').bottom / etc was sometimes wrong, I found what causes this, if a scroll bar is displayed on screen it will cover the panel and not be taken into consideration. It appears to be about 16 pixels so I've modified my code to take this into consideration.

**Comment by Flyer53** [comment]
Thanks for your investigation and extra demo 😄 
The scrollbars ... yes that's a point. But as far as I know there's no reliable way to detect scrollbar width/height (at least not for elements other than body). So I don't see how I could account for scrollbars automatically.

`panel.overlaps('window')` issue: I'm a little confused here because I can't see anything wrong. Could there be some kind of misunderstanding? Or misleading docs for the `overlaps()` method? Please consider I'm an amateur programmer and English is not my mother tongue. So my phrasing might not be very good sometimes.

`panel.overlaps('window').overlaps` is supposed to return `true` if even a single pixel of the panel is still visible in the window (viewport) and returns `false` if the panel is fully outside the window boundaries.
Maybe it's not clear that `overlpas()` is **not** called continuously unless you take care of that. In the docs for `overlaps()` the method is called inside the `drag callback` so its return value updates permanently. But in the tooltip example `overlaps()` runs just once and is not updated on a window resize event.

**Comment by SeanBannister** [comment]
Sorry I should of read the docs and not presumed. I thought `panel.overlaps('window').overlap` worked in reverse to the way it was programmed. As in "Is the panel overlapped" = true.

Thanks again.

**Comment by Flyer53** [comment]
No problem at all ...
How about the original positioning issue? Anything more to do about that or does the extra option `opacity` as shown in [example 4](https://alpha.jspanel.de/api.html#extensions/tooltip/example-4) do the job?

**Comment by SeanBannister** [comment]
Yes, thanks a heap for that `opacity` option it works great 🙂

[Here's a development example](http://www.seanbannister.com/demo/) of what I'm working on just in case your interested. Still a few bugs and not finished, just hit the tab key anywhere inside one of the text boxes, you'll notice the panel displays next to the caret/cursor (there's sometimes an alignment bug but its my issue).

I thought you'd be interested to see that I reused your [autoclose progressbar](https://jspanel.de/api.html#options/autoclose) and turned it into a loading bar as I have a process that will take some time to complete (I'm currently faking this process in the example). Maybe an idea for a future version of jsPanel to allow the progressbar to be specified outside of autoclose (could be handy for ajax requests and much more). I know how long my process will take but for unknown length processes you could use one of those progress bars [that just keep going](https://freefrontend.com/assets/img/css-progress-bars/light-progress-bar-HTML-CSS.gif).

You also might be interested to know I switched from regular jsPanels to tooltips and then back again. I was hoping to have an arrow on the jsPanel pointing at the caret. But the tooltip implementation is expecting mouseover or click events on an element, it doesn't expect the tooltip to be generated by another event such as a keyboard shortcut, etc. I got it working but I had to implement a number of workarounds and it just started feel to hacky. Maybe another idea for a future version, allow a tooltip that doesn't require hover/click on an element.

Thanks again, really appreciate it!!! I'll send you demo of my software when things are completed.

**Comment by Flyer53** [comment]
My pleasure,
Thanks for the demo ... seems to work quite well so far.
Your ideas about the autoclose progressbar and tooltip improvements are definitively worth thinking about 👍  Maybe once I have v4.11.0 finfished ...

I made a minor update to jsPanel and call it [v4.11.0-beta](https://beta.jspanel.de/downloads/jspanel-4.11.0-beta.zip) now. **Option opacity now expects a number value.** No need to wrap a zero in a string.

Looking forward to a demo 😄

**Comment by SeanBannister** [comment]
Is there a GitHub push of v4.11.0-beta, was going to add the GitHub commit to my package.json#dependencies to make it easier to manage.

**Comment by Flyer53** [comment]
Not yet. Might be there later today or tomorrow ...

**Comment by Flyer53** [comment]
Now there is _**v4.11.0-beta**_ on GitHub and NPM as well

**Comment by SeanBannister** [comment]
Thanks dependency struggles sorted :)

**Comment by Flyer53** [comment]
@SeanBannister 
Thinking about a more general use of the autoclose progressbar as you proposed. I looked at the code and found that it's quite easy already. See https://beta.jspanel.de/#properties/progressbar where I added an example.
I wonder whether it makes sense to add extra code?

**Comment by SeanBannister** [comment]
That's great, I just replicated the functionality I was using with this method really easily. Did some custom styling in CSS and just used `panel.autocloseProgressbar.classList.add('active');` in the callback. Probably no need to add extra code, anyone who wants a progressbar will most likely have a custom implementation. Thanks this is brilliant and simplified my codebase (I was originally injecting the HTML manually to make it happen).
