### ISSUE TITLE
Hiding the panel, then redisplay it

### ISSUE THREAD

**Issue by roamhacker** [Flyer53/jsPanel4#133]
Very nice component!!

I want to hide the panel (not minimize), then bring it back. I see I can close() the panel and that it is still in memory, but I don't see how to show it again.

Thanks

**Comment by Flyer53** [comment]
@roamhacker 
As far as I understand from our Twitter conversation this issue is fixed using option [minimizeTo](https://jspanel.de/#options/minimizeTo). Correct? So unless you have more questions concerning this I'd ask you to close the issue.

Regards,
Stefan

PS: How about the [layout extension](https://jspanel.de/#extensions/layout)? Do you get along with it?

**Comment by roamhacker** [comment]
Yes, this is resolved. Really an amazing library.Thank you very much for your work on it.
