### ISSUE TITLE
Document scrolls to the top of the page when creating new panel

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel4#14]
Hi Stefan 
I do not know what I'm setting wrong with jsPanel
the panel always jumps to the top of the page and the User loses its location and the content that is being viewed
I would be happy if you could find the problem in the example
http://www.admin.technion.ac.il/avi/

Thanks
your
Hefner Avi

**Comment by Flyer53** [comment]
Hi Avi,
The first thing I see is that you use an invalid setting for option position.
You use `position: 'center-left'` but `'center-left'` is not a valid value for position. If you want the panel to be on the left side and vertically centered use `position: 'left-center'`.
Try changing this first please. Maybe that's all to fix ...

Best regards,
Stefan

**Comment by AviHafner** [comment]
Hi Stefan

1) I am Apologetic,
I cannot bring the panel to the top of the viewport,
The panel jumps to the top of the page.
2) In chrome when I open more tools, developer tools, toggle device toolbar,
 To activate the phone emulation, when I click on the closing icon in the toolbar the event triggered the event on the layer underneath it.
3) I got rid of jquery framework and wrote the basic functions like
$(document).ready, .Closest,. Find.

As before, I would be very happy if you could advise me on how to improve and optimize the code
You can find example in 
http://www.admin.technion.ac.il/avi/

Yours 
Avi Hafner

**Comment by Flyer53** [comment]
Hi Avi,
a few more issue:
+ you don't need your own polyfill for `Element.closest()` because jsPanel already includes this polyfill
+ in your code you use `modify: this` in `option.position`. That doesn't make any sense because the parameter `modify`expects a function as value.
+ there is nor theme `light` in jsPanel4 anymore. Just leave it out for testing

But points above won't have anything to do with the scroll issue...
+ your sample code is a bit hard to read. You mix up meta, link, script and style tags all over the place. It would be a lot better to read (and help) if there would be some structure in your sample page. It simply doesn't improve readability when you have to jump from top to bottom back and forth to read the js
+ so far I can't identify anything causing this scroll issue. My recommendation would be be to strip anything from the test code that's not absolutely necessary and start from there. E.g. in this kind of app I don't see a reason for this passive event listener thing.
+ download latest [jsPanel4-beta](http://beta.jspanel.de/downloads/jspanel-4-beta.zip) - maybe it changes something
+ I'll try to find something thought ...

Best regards,
Stefan

**Comment by Flyer53** [comment]
Ok Avi,
I created an example that basically does what you want (as far as I think) using the latest beta.2.22 (link above)
+ It's a basic example without a lot of styling
+ needs only a fraction of the js of your example
+ no extra polyfills
+ **no scrolling issue** (at least on the mobiles I have for testing)
+ **no more underlying elements being triggered** (so no need for a footer toolbar)

http://alpha.jspanel.de/docs/demos/avi-sample.html

Hope it helps,
Stefan :)

**Comment by AviHafner** [comment]
Stefan ,
Thanks a lot
For all the efforts you devote to me
I am out of work
I will look carefully in what you have written in the coming days

Best regards,
Avi

**Comment by AviHafner** [comment]
Hi Stefan
Thanks for the guidance, I am looking for a source to learn knowledge in the transition from jquery to Writing Pure JavaScript.

One Sources to learn that I found is
https://developer.mozilla.org/en-US/docs/Web/API/Element/closest
My question if this source is enough or you know better sources of learning.

Now to the problem with the panel.
1)	I found the reason that the click to open the panel jump the to the top of the page,
I changed the element that trig the panel from <a to <button and the problem solved.

2)  The problem that remains,
I use the position as: 
 position: {
                    my: 'left-bottom',
                    at: 'left-center',
                    offsetY: -20,
                    minTop:50,
                    of: this
                },
In some cases the panel is opened when part of the panel is hidden,
I need to see the full size of the panel in all the cases in the viewport.  
If I omit the parameter position, you put the panel always in the center and this is good.

 But I want to use the parameter position.
You can see example in:
http://www.admin.technion.ac.il/avi/

Best regards,
Avi

**Comment by Flyer53** [comment]
Hi Avi
The Mozilla Web Docs are almost always my first place to look whenever I need infos about a specific js feature. Other useful websites are the ECMAScript 6 compatibility table at http://kangax.github.io/compat-table/es6/ and especially for css compatibility questions https://caniuse.com/
And never forget to check compatibility with the browsers you need to support!

But remember that you do not need to work without jQuery just to use jsPanel4. 

Now your positioning question:
What you need is a minTop setting that is calculated when the panel is created because when you use the position parameter `of` the minTop value is relative to the top of the document and not to the top of the viewport. The parameter `minTop` currently does not support a "normal" function as value but you can use an **[IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)** (Immediately Invoked Function Expression), a JavaScript function that runs as soon as it is defined.

Try using:
```javascript
minTop: ( function(){ return window.scrollY + 50; } ) ()
```
within your position setting. I didn't try it with your code, but it should work. Give it a try 😏 

Happy coding,
Stefan

**Comment by AviHafner** [comment]
Hi Stefan
Thanks a lot,
Your answer to see the panel in all the cases is perfect,
And I set the position to:  
position: {
                    my: 'left-bottom',
                    at: 'left-center',
                    offsetY: -35,
                    minTop: (function () { return window.scrollY + 50; })(),
                    of: this
                },

The reasons that I prefer to use pure JavaScript instead of jQuery:
1)	Using in Pure JavaScript We can write anything that jQuery offers and I think we can write better code than jQuery offers.
2)	Release changing versions in jQuery happens one in the year at best and sometimes more,
that Is not enough ,
one example :
the support of passive event will arrive sometime in the future version 4.
3)	The better approach for   $( document ).ready() :
the $ (document) .ready () Performs when readyState: complete
And that means all the content of the page has loaded
its include all the css images and frames.
The similar approach in pure JavaScript code is to put the JavaScript in the bottom of the page before the </boody> tag and it’s execute  after all the contents loaded.
4)	I think the best way to trig the function is when the
readyState: interactive
and it's happen Before loading the CSS and images and the iframes.
I put the script in my projects in the top of the <head> tag
So that the page will be released to the client faster,
Please read the - Page lifecycle: DOMContentLoaded https://javascript.info/onload-ondomcontentloaded
5)	The disadvantage of making page load in this way, is not to knowing the
$ (document) .width at this stage , My opinion  that we don’t need this information for 99% of the cases
6)	I check the readystate in one of my projects  and the times:
event.target.readyState=interactive  08:13:35
event.target.readyState=complete  08:13:37
Stefan:  I'm curious to know what you think about this issue


 Best regards,
Avi

**Comment by Flyer53** [comment]
Hi Avi
Glad to hear it works as expected 😄 

1. Agreed. The main reasons I try to do jsPanel without jQuery are
    + jsPanel should work with any other js framework
    + to get a better understanding of js
2. True, they could release more frequently
3. You're wrong here Avi. A handler passed to `$(document).ready()` is called when the DOM is ready for manipulation. It does **NOT** wait for images and other assets to be loaded. See http://api.jquery.com/ready/
4. I don't think there is a definite wrong or right to the question where to load scripts in a document. It depends ... But in general (from the link you posted above)

    >When the browser initially loads HTML and comes across a `<script>...</script>` in the text, it **can’t continue building DOM**. It must execute the script right now. So `DOMContentLoaded` may only happen after all such scripts are executed.
External scripts (with `src`) **also put DOM building to pause** while the script is loading and executing. So `DOMContentLoaded` waits for external scripts as well.

    So unless you have a good reason to load a script at the top of the page it's normally better to load them at the end. In other words, a script loaded at the end does not stop the DOM from being loaded.

5. I think there's more to it. A script loaded at the top knows absolutely nothing about the DOM to be loaded afterwords.
6. It's not that easy I think. E.g. you load Font Awesome at the top of the page. What if the server needs a few more seconds to answer your request? In the traditional way the page would remain blank until the resource is loaded ... unless you use `async`. For reliable page load times you have to eliminate any inconsistencies first.

So what's the answer to the question where to load scripts? My answer: It depends 😏 

Best regards,
Stefan

**Comment by AviHafner** [comment]
Hi Stefan
Thanks a lot


Best regards,
Avi

**Comment by Flyer53** [comment]
Always welcome Avi :)
Take care,
Stefan
