### ISSUE TITLE
containment when parent position is absolute

### ISSUE THREAD

**Issue by balage1551** [Flyer53/jsPanel4#150]
**Describe the bug**
When the parent container is absolute positioned, the containment ignores it's size. For example:

```
    <div class="placeholder">

        <!-- The declaration of the panel, whith drag containment -->
   </div>
```

CSS:
```
div.placeholder {

    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    border: 1px solid orange;
}
```

My page only contains panels (no out-of-panel contents). When the panel is displayed with predefined position, it appears as it meant to be. But when I try to move it by dragging, it "disappears", or as a lighter 1px area hints, it is contained to a 0px high content.

**To Reproduce**
1. Create a top level parent with the above CSS. (It fits the viewport all the time, meant to mark containment area, in spite there are no top level elements.
1. Create a panel with dragit : { containment: 0 }
2. Try to drag the panel
3. The panel disappears to the top 1 px.

**Expected behavior**
The containment respects the size and position of the parent regardless it's definition.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: any
 - Version 4.1.12

**Additional context**
A would appreciate any workaround for the scenario.
One more note: I can't put all to top (body) level, because I use it with Vue where a container div is required for each component.

**Comment by balage1551** [comment]
Meanwhile I've found a workaround:

```
body {
    height: 100%;
    width: 100%;
    overflow: hidden;
}
```

Nevertheless, the anomaly still stands.

**Comment by Flyer53** [comment]
@balage1551 
Hi there,
I miss some information:
- where do you append the panel to?
- what is the complete panel configuration?

So I assume the following:
Your panel config does not use **option** `container` (so it defaults to `'window'`) and you want to confine dragging to the window.

If that's correct there is nothing wrong with jsPanel. But you missed an important fact which you can see in the screenshot below:
![Unbenannt](https://user-images.githubusercontent.com/6769021/105728173-217d6d80-5f2c-11eb-83fa-fcc88049801b.jpg)

Since all elements in the page (the panel and your `<div>`) are positioned absolute the `<body>` element has a height of 0 (zero) which is standard behaviour.

**Documentation for `position: absolute`: "The element is removed from the normal document flow, and no space is created for the element in the page layout...."**
See https://developer.mozilla.org/en-US/docs/Web/CSS/position

Now tell me how you want the containment to work within an element with no height. Dragit containment still works just fine, but because the bottom containment is the last one checked the panel's bottom is alligned with the bottom of the `<body>` element which has a height of 0 (zero) resulting in a panel out of view. If you check you will note that left and right containment works as intended.



Conclusion:
If your page doesn't include anything that results in a positive height of the `<body>` element you need to deliberately set a height. Just as you did to make it work in your example.

**Comment by balage1551** [comment]
You were right. The `container` option was missing.
