### ISSUE TITLE
Panel stops moving when dragging quickly vertically

### ISSUE THREAD

**Issue by farowebshare** [Flyer53/jsPanel4#156]
Thank you for your work on this panel component.

We have encountered a problem with dragging the panel in our web site. When dragging the panel (on its header bar) quickly up or down, the panel stops following the mouse cursor. Strangely, moving the mouse cursor to the left or right doesn't show this effect.

The connection is not totally lost, though. The panel gets dragged again if you return to the header bar with the left mouse button still pressed. Or if you move the mouse cursor above another UI element of our web site. The panel stays in its old position as long as the mouse cursor is anywhere in the big canvas element. But if you move the mouse cursor over any other UI element, like a button, or the sidebar menu, the panel jumps to the new position.

No specific container is set for the panel, so it's window.

I have the problem in Chrome and Firefox. But in Firefox it's worse because you really don't have to be fast to lose connection.

I do not have this problem with the example panel on [jspanel.de](https://jspanel.de/) That one works fine.

If you want to see the problem in action, go to [websharecloud.net/...](https://websharecloud.net/?v=pv&t=p:default,c:panoramaview,h:f,m:t&pv=pv1&pv1=vt:3d,u:7a2070a2-7b5f-455b-abc6-1489b1d62ae6,cf:65.00,dh:f,st:f,cx:7.21812,cy:-8.32812,cz:5.47181,p:3.92699,t:-0.33984&p=p:funpark) Then click on the little gear button in the bottom left corner. Then click on the button with the two boxes and the clock. Then a jspanel is opened that has the described behavior.

**Comment by Flyer53** [comment]
@farowebshare 
Hi there ... and thanks for the report.
I see the problem and it probably has to do with some particularities of the `<canvas>` element. If you drag the panel over the menu on the right hand side the effect you describe does not occur. Since I never worked with `<canvas>` so far I can only guess that a `<canvas>` element somehow behaves a bit like `<iframe>` elements. I'll make a few tests to find out whether I can handle this the same way as with `<iframe>` elements. It will take a few days though ...

Regards,
Stefan

**Comment by Flyer53** [comment]
@farowebshare 
Ok, my first assumption doesn't seem to be true.
I created a quick demo: https://alpha.jspanel.de/docs/demos/test-canvas.html
Everything seems to work just fine, so there must be something else.

There's one thing I noticed in your demo: If I remove the `<canvas>` element just after the comment "Transparent canvas, only for mouse events. Previously needed for IE 10 compatibility, ..." the issue seems to be gone.

![Unbenannt](https://user-images.githubusercontent.com/6769021/111865006-ae5d0a00-8964-11eb-882c-d7e82ccc7f3d.jpg)

**Comment by farowebshare** [comment]
Thank you for the very fast reply!

Removing this canvas element only solves the dragging problem when done when the page is already loaded. If you remove it in the code already, it doesn’t work. (Removing it from the fully loaded page makes navigating in the 3D view impossible.)

However, this hint pointed me in the right direction:

Our mouse event listener for the 3D view starts receiving mouse events (of type jQuery.Event) again when the pointer is at a certain distance from the header bar. That event is then handled, doing nothing, and the menu doesn’t receive it. One would expect our mouse event listener would receive mouse events either never in this case or immediately when the header bar is left. But that would be too easy I guess…

Knowing this, I have now successfully tested to temporarily disable our mouse event listener in a jspaneldragstart handler and enable it again in a jspaneldragstop handler.

**Comment by Flyer53** [comment]
Thanks a lot for the info 👍 
So for the time being I assume it's not a bug in the jsPanel script and consider the issue solved!?
In case you investigate this any further and find something helpful I would appriciate if you let me know.

Happy coding,
Stefan

**Comment by farowebshare** [comment]
Yes, I currently consider this issue solved for us. Since the solution described above seems to work fine, I won’t dive deeper into our complex mouse event listener setup.
