### ISSUE TITLE
Drag & resize not working with touch on desktop

### ISSUE THREAD

**Issue by JackD83** [Flyer53/jsPanel4#170]
**Describe the bug**
Drag & resize not working with touch on desktop (windows and linux).

**To Reproduce**
1. Go to 'https://jspanel.de/'
2. Try to move the example panel using touch 
3. The panel can not be moved

**Expected behavior**
The panel should be movable using touch

**Desktop:**
 - OS:  Windows 10, Debian 11
 - Browser: Chrome 94, Edge Chromium, Firefox

**Additional context**
Everything is working on mobile, and with mouse interaction. The problem only exists with touch on the desktop.
Enabling dom.w3c_touch_events.legacy_apis.enabled in firefox or adding --touch-events to chrome fixes the issue,

The same issue breaks native html drag&drop

**Comment by JackD83** [comment]
Thanks! I will give it a try and report back.

**Comment by Flyer53** [comment]
@JackD83
It's been 4 weeks now. Some feedback would be nice...

**Comment by Flyer53** [comment]
I had an issue with the `containment` setting of options `dragit` and `resizeit`. When using `containment` dragging/resizing stopped before reaching the left boundary set. But that problem seems to have vanished. At least the quick check I just made didn't show a problem.

I just checked with a Galaxy Tab S3 using Mouse, Touch and Pen.

Using a pen seems to be a bit tricky sometimes when the pen is already recoginzed (and thus a pointerdown is registered) but not touching the surface yet. In this case it happened sometimes that a pointerup was not recognized.

**Comment by Flyer53** [comment]
@JackD83 
I just released v4.13.0 which includes the change you already got. In addition there's a new method `jsPanel.usePointerEvents()` to disable/enable the use of pointer events.
If you don't have anymore questions concerning this issue ... please close it.

**Comment by Flyer53** [comment]
Fixed with v4.13.0
