### ISSUE TITLE
Panel retains fixed height if content height = auto

### ISSUE THREAD

**Issue by TerrapinSoftware** [Flyer53/jsPanel4#180]
**Describe the bug**

In the options, set `contentsize: "auto"` to have the panel resize to the size of the content. The panel itself keeps a fixed height (the style attribute sets the height), even if the content area does have the style attribute `height: auto`.

**Expected behavior**

The panel itself should also have the height set to "auto". See screenshot. ![](https://user-images.githubusercontent.com/55277486/166122127-6359a2af-8107-4b91-905f-584775f87f50.jpg)

Fix: in options.callback(), add:

    if (options.contentSize === "auto")
        panel.style.height = "auto";

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.3.1
 - BrowserCHrome, Safari, Firefox, Edge
 - Version 4.13.0

**Comment by Flyer53** [comment]
Hi there.... and thanks for the report,
I will need a few days for a more detailed answer since I won't be at home for the next 8 days probably.
Until then,
Stefan

**Comment by TerrapinSoftware** [comment]
That would be options.content.

Am 9. Mai 2022 10:38:23 schrieb Stefan Sträßer ***@***.***>:

**Comment by daumling** [comment]
I tried your suggested fix, and it works. I just wonder where my code fails when I assign a DOM node to `option.content`. jsPanel should be able to figure out the panel height correctly. Could it be related to the fact that my panel does neither have a header nor a footer?

**Comment by Flyer53** [comment]
Ok, I finally identified why the panel's **style.height attribute** ends up having a pixel value even if option `contentSize`/`panelSize` is set with `'auto'` for height:
After the panel is created, sized and positioned one of the final steps is to save current position and size in order to have values to set when a panel is normalized after being maximzed, minimized and so on. In this process the style.height attribute is set to the actual pixel value. Whenever a panel's position or size is changed this process runs again. But this does not affect the initial sizing of the panel since caching of position/size is one of the last things happening.

So why is your panel not properly sized?
To be frank ... I don't exactly know. I can only guess so far. Is some of the content loading asynchronously? Could there happen something else causing a reflow resulting in another height?
Whether there is a relation to the missing header/footer is something I have yet to look into.

**Comment by Flyer53** [comment]
@daumling
Is this still an issue?
I found a piece of old code that seems to be obsolete and possibly has an effect on this issue. Something I need to check out ...
