### ISSUE TITLE
Add TypeScript Support

### ISSUE THREAD

**Issue by gyenabubakar** [Flyer53/jsPanel4#195]
**Describe alternatives you've considered**
For now, I use `@ts-ignore` to hide the error when importing the `jspanel4` module.

**Additional context**

<img width="911" alt="Screenshot 2022-09-22 at 11 31 20 AM" src="https://user-images.githubusercontent.com/26672526/191735636-f6df78f2-7690-4925-b34e-16ee8f28b4cc.png">

**Comment by Flyer53** [comment]
@gyenabubakar Hi there,
I personally don't use Typescript at all and don't see any reason to do so for now.
So I'm sorry ... I won't implement any changes concering Typrscript.
Regards,
Stefan

**Comment by markhalliwell** [comment]
> I personally don't use Typescript at all and don't see any reason to do so for now.

In enterprise level projects, strongly typed code is a requirement to ensure IDEs and compilers catch human level errors/typos.

For this reason, I went ahead and typed this project all out and put it in a custom declaration file inside the project. I wanted to add it to https://github.com/DefinitelyTyped/DefinitelyTyped (would give the ability for users to `npm i @types/jspanel4`), but don't have the time to write the necessary tests for all these options.

https://gist.github.com/markhalliwell/e984bbca9741d0501f08937a9351f323

**Comment by Flyer53** [comment]
@markhalliwell 
Hi Mark,
Thank you very much for the work you put into this issue. I really appriciate that and understand your reasoning. But please understand that I'm simply an amateur programmer. Getting jsPanel to the point where it actually is (far beyond anything I ever planed) was some hard work for me.
And since I'm already retired for some years now my focus is more on enjoying live 😏. I guess that jsPanel version 4.x is at the end of its developement and wether I'll ever start a version 5 ..... I don't know.
Best regards,
Stefan
