### ISSUE TITLE
[QUESTION] Replacement for "contentOverflow" property

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel4#26]
Hi,

I've just noticed that v4 no longer supports `contentOverflow: 'scroll'`. What do you suggest we should use as replacement?

Thanks!

**Comment by Flyer53** [comment]
Hi Temuri,

`option.contentOverflow` will be back in the next update/release. But probably with a different (shorter) syntax.

**Comment by Flyer53** [comment]
@temuri416 
Download the latest [nightly build](http://alpha.jspanel.de/downloads/jspanel-4-beta.zip) and option.contentOverflow is back.
Check the [docs](http://alpha.jspanel.de/docs/#options/contentOverflow) because the syntax is different now.

I also changed the default settings for overflow of the content section:
`overflow-x: 'hidden'`
`overflow-y: 'auto'`

**Comment by temuri416** [comment]
Great, as ever! It's working :)

Thanks!
