### ISSUE TITLE
documentation page

### ISSUE THREAD

**Issue by itpmngt** [Flyer53/jsPanel4#3]
Hi - great stuff - version 4 is really welcome - Thank You

Small tweak on the documentation page of the context-menu extension (http://jspanel.de/docs/#extensions/contextmenu) is missing the second example description (and button for first example)

Best

**Comment by Flyer53** [comment]
@itpmngt 
Hi Joe, thanks for your input :)
Code for contexmenu example 2 is added to the docs.
Example 1 doesn't need a button because the whole code sample already responds to a right-click
![unbenannt-2](https://user-images.githubusercontent.com/6769021/33793565-9afb5e0e-dcb9-11e7-9e69-6e7851aad95f.jpg)

Happy coding,
Stefan
