### ISSUE TITLE
Some changes are not working And not documented between version 3 and version 4

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel4#6]
Hello Stephen
I started to  test version 4 on my projects
Few changes that I have not found documentations.

1)
 in Version 3 we create panel with 
**panel = $ .jsPanel**
in Version 4
we create panel with
**panel = jsPanel.create**

2) What is the equivalent of 
**this.content.css** ({
                 'background': 'rgb (232, 232, 232)',
                 'padding': '10px',
                 'box-shadow': 'inset 2px 2px 2px 0px #dddddd;'
             });
**this.content.css** is not working in version 4 

**What are the other changes that working differently from version 3 in version 4  ?**

yours 
Avi Hafner

**Comment by Flyer53** [comment]
Hi Avi,
.css() is a jQuery method. And because jsPanel 4 doesn't need jQuery anymore you can't call .css() directly on this.content
Please look for jsPanel.setStyle() in the docs for the global object jsPanel.

Sorry for this very short answer. I'm away over Christmas/New Year and my only internet access is my mobile phone.

Best Regards, Stefan

**Comment by AviHafner** [comment]
Hi Stefan
I wish you a merry Christmas and happy new year.

Every major version of jsPanel has a change in the form of use, I understand and I think that  it’s right.

Please add support for version 4 on **headerControls: iconfont**

I put version 4 into Production in one of my projects with a  little use of jsPanel .

Yours 
Avi Hafner

**Comment by AviHafner** [comment]
Hi Stefan
Some minor issues about version 4
1) When define **animateOut: 'animated bounceInRight’**,
It destroyed the panel object and close icon on the header not working.
You can see the example in [ www.admin.technion.ac.il/avi
](www.admin.technion.ac.il/avi).

2) How can I justify right, the Buttons on footerToolbar?
3) What is the equivalent of dataFilter: in version 4 to remove script from contentAjax
4) If you can check the example and can give my advices how to improve the code.
5) Please add support in version 4 to headerControls: iconfont

Yours 
Avi hafner

**Comment by Flyer53** [comment]
Hi Avi,
**one very important fact to remember is that jsPanel v4 doesn't make use of jQuery anymore.** As a result you cannot use jQuery methods the way you are used to with previous jsPanel versions. So for example the **content** property in jsPanel v3 was a jQuery object where you could chain jQuery methods to. In jsPanel v4 the **content** property refers to the HTML element which doesn't have a method .css() for example. But you can make it a jQuery object by wrapping it in the $() function like ...
```javascript
jsPanel.create({
    content: '<p>Some sample text ...</p>',
    callback: function() {
        // wrap content in the $() function to make it a jQuery object
        // then you can use .css()
        $(this.content).css({padding:'20px', fontWeight:'bold'});
    }
});
```
<hr>

1. As far as I can see in your example you do not load a css file that provides the animations. There are so many good css libraries that provide excellent css animations that I don't see a need to include my own ones (except one). See the docs at http://jspanel.de/docs/#options/animateOut
2. By default the footer section is a css flexbox. I suggest that you look at example 2 at http://jspanel.de/docs/#options/footerToolbar and see what the default css for the footer is. Then you just need to adjust the css to your needs. Try setting the footer css to **justify-content: flex-start**
3. **dataFilter is a jQuery.ajax() setting**. This setting is not available in jsPanel v4 because it doesn't use jQuery. So your option.contentAjax needs to look something like
```javascript
jsPanel.create({
    contentAjax: {
        url: '../to/your/resource',
        done: function (panel) {
            // assign server response to a variable
            var value = this.responseText;            
            // then do whatever needs to be done with the response (value)
            // and append the processed response to the panel
            panel.content.innerHTML = value;
        }
    }
});
```
See http://jspanel.de/docs/#options/contentAjax for more details. If I remember your last contentAjax question about dataFilter correctly you might want to take alook at the parameter *evalscripttags* of the new option.contentAjax
4. Give me some time to check out your example ...
5. In jsPanel v4 iconfont is a dedicated option and not part of option.headerControls. See http://jspanel.de/docs/#options/iconfont

If something is still unclear ... don't hesitate to ask 😏 

Best Regards,
Stefan 😄

**Comment by AviHafner** [comment]
Hi Stefan
your answer is perfect answer . 
I will study your answer  and implement  it.
thanks a lot
yours
Hefner Avi
