### ISSUE TITLE
Import as Node.js module

### ISSUE THREAD

**Issue by dev-zetta** [Flyer53/jsPanel4#61]
Hello there,

it is impossible to import the jsPanel4 via require(), there is no module.export... Are chance of adding it? :)

**Comment by Flyer53** [comment]
@dev-zetta 
Hey there,
Well, since there are native javascript modules now the jsPanel download package includes the folder `es6module` containing jsPanel as native javascript module. I don't plan to create jsPanel versions for other "module systems". And as far as I know native ES modules are comming to node as well.
https://medium.com/@giltayar/native-es-modules-in-nodejs-status-and-future-directions-part-i-ee5ea3001f71
Maybe the link helps a bit.

**Comment by dev-zetta** [comment]
Yep, but that is just an experimental feature and requires to use .mjs scripts instead of standard .js.

I have a Electron + Ember project and your lib is importer thru npm, however I had to modify it, so it can be loaded using require(). Its impossible to use import syntax, as it Electron does not understand that.

All I had to do, is add the following code to your lib: module.exports = jsPanel. I believe that most packaged that are distributed via npm have the main script exported using module.export in index.js.

Anyway, thank you for prompt reply. Have a nice day.

**Comment by Flyer53** [comment]
@dev-zetta 
You know, when I started with v4 it was one of my primary goals to get rid of all dependencies. Plain javascript should work with all other js libraries I guess. And as an amateur programer I simply don't have the expertise to create adaptions for every other framework/library.
Take care,
Stefan

**Comment by dev-zetta** [comment]
@Flyer53 I just made a PR to support CommonJS :)
