### ISSUE TITLE
Is it possible to dock a panel within the document?

### ISSUE THREAD

**Issue by jfrank14** [Flyer53/jsPanel4#64]
I'm trying to create an interface where a panel is shown inline within the document, but I want to be able to undock it so that it's removed from the document flow, but then dock it again within the document where it was, instead of minimized to the bottom of the page. Is that something that jsPanel supports?

**Comment by Flyer53** [comment]
I'm not sure whether I understand your intention correctly. So let's check that first:

1. You start with a panel that is appended to `document.body` or some other `element`. So it's positioned `absolute` and scrolls with the window.
2. Then you intend to change panel status in a way that it is positioned `fixed` within the browser viewport and does not scroll with the window.
3. And then you want to revert panel status back to where it started.

Is that correct?

**Comment by jfrank14** [comment]
I was thinking it would be positioned statically, and thus take up space in the layout:

CONTENT
PANEL
CONTENT

and then when you undock, it would become fixed:

CONTENT                                                              DRAGGABLE PANEL
CONTEXT

In other words, the subsequent content would slide up to take the place of the panel when it's undocked, and then slide down again if you re-dock it.

**Comment by Flyer53** [comment]
No, that's not how a jsPanel works by default.
+ a jsPanel that uses option `container` set to `'window'` (which is the default) is appended to the `body` element and positioned `fixed`.
+ if option `container` is set to `document.body` or any other element the panel is appended to the specified container element and positioned `absolute`. 
+ the script does not have a built-in option to position a panel `static`.

However, you can of course set css `position` of an existing panel to `static` in order to make it part of the normal document flow. Depending on how your page works you might need to move the panel to the intended position. And whenever need reset css `position` to 'absolute'.

**Comment by Flyer53** [comment]
I created a simple demo: https://jspanel.de/docs/demos/static.html

**Comment by jfrank14** [comment]
That is really excellent. Let me try it out in my project to see how it works. Thanks so much!

**Comment by Flyer53** [comment]
Added a second demo that toggles the extra control's icon depending on whether the panel is positioned `absolute` or `fixed`.

https://jspanel.de/docs/demos/static-2.html

Remark: This example also uses a different way to use the Font-Awesome icon. It might not work on your site unless you have Font-Awesome 5 Pro.

**Comment by Flyer53** [comment]
... and a third demo that toggles the panel between position `'static'` and `'fixed'`

https://jspanel.de/docs/demos/static-3.html

**Comment by Flyer53** [comment]
@jfrank14 
How about this issue? Could you put something together the way you wanted?

**Comment by jfrank14** [comment]
I tried it and it worked quite well. Sorry, I meant to add that to thread but it slipped my mind. Thanks for the assistance!
