### ISSUE TITLE
Drag/resize issue in simulated mobile view in desktop browser on device that supports mouse & touch input at the same time

### ISSUE THREAD

**Issue by akstek** [Flyer53/jsPanel4#65]
If you have a device which supports mouse an touch imput at the same time you can not drag or resize a panel by touch.

You can simulate and reproduce this with chrome:

1) Load the script
2) Open a panel
3) You can drag the panel with mouse
4) Open chrome dev tools, switch to mobile view
5) Try to drag or resize the panel -> not possible
6) Reload the script while in mobile view  -> now you can drag / resize also with touch and mouse

**Comment by Flyer53** [comment]
Well, the only device I have that supports touch and mouse is an Android tablet and there it works very well (with mouse, "normal" touch and pen).
What you describe with point No 6 tells me it works on your device as well. And I want to back this with the fact that **on devices that support touch and mouse input the necessary handlers are attached to mouse *AND* touch events**.
I tend to think that the issue you describe is a result of how Chrome handles the switch between desktop browser and simulated touch device.
I allowed myself to rename the issue since the original title implied that touch is not working at all.
<hr>

**However, this might soon be irrelevant because as of the next update jsPanel will use only pointer events in browsers supporting them.** As of today **https://alpha.jspanel.de/api.html** already runs with a preliminary **v4.5.0** you could check (a download is not available yet).

**Comment by akstek** [comment]
Sorry for the delay but I was on vacation ;-) 
I can confirm that with the alpha Version of 4.5 the issue is gone.
On the current  4.4 version the issue still exits for me on ubuntu 10.04.1 LTS  using Chromium 71 and Chromium 63.

**Comment by Flyer53** [comment]
No problem ... was away myself until yesterday 😏 
Could it be that it's a platform issue? Ubuntu 10.x is quite old (even as LTS).
If you want to give it a try [download v4.5.0-alpha2](https://alpha.jspanel.de/downloads/jspanel-4.5.0-alpha2.zip)

**Comment by Flyer53** [comment]
There is a new alpha to test:
https://alpha.jspanel.de/downloads/jspanel-4.5.0-alpha7.zip

Changelog:
+ jsPanel now uses **pointer events** if supported
+ **bugfix** in `jsPanel.position()` concerning the use of the **dock extension**
+ **bugfix** in `minimize()` concerning the use of an image as background
+ **option theme** got numerous updates:
  + additional built-in themes
  + updated built-in theme colors
  + all built-in themes are are now "normal" color themes &rarr; less CSS
  + recoded bootstrap theme support &rarr; no more bootstrap adjustments in *jspanel.css* needed
  + option theme can now be used with an object as value &rarr; more theming options and better support of images (includes css gradients) as panel background
+ **added** parameter `status` to the callbacks `onbeforemaximize`, `onmaximized` etc.
+ **added** parameter options `'hide'` and `'show'` to panel method `setControlStatus()` parameter `action`

**Comment by akstek** [comment]
De provided download link is broken.

**Comment by Flyer53** [comment]
Oh sorry,
a typo in the file name ... fixed.
But I suggest you wait til tomorrow, then I'll have another update to alpha13

**Comment by akstek** [comment]
OK. We will wait for the new alpha release

**Comment by Flyer53** [comment]
Ok ... there it is

https://alpha.jspanel.de/downloads/jspanel-4.5.0-alpha14.zip

**Comment by Flyer53** [comment]
**v4.5.0-alpha14** includes a complete recode of the `close()` method which is now a method of the global object `jsPanel`. The individual `panel.close(cb);` just calls `jsPanel.close(panel, cb);`
This was necessary to fix a long standing bug. Not fully tested yet, so I hope it doesn't make any problems ;)

And the following new feature which is still some work in progress
https://alpha.jspanel.de/api.html#options/onparentresize

**Comment by akstek** [comment]
You are aware that safari osx+ios does not support pointer events?
https://caniuse.com/#feat=pointer
Or is this table outdated? Can't check it, cause I don't have access to osx/ios enviroment

**Comment by Flyer53** [comment]
The Pointer Event API is only used when supported by the browser. Otherwise Touch and/or Mouse Event APIs are used.
My check on an iPad Air works fine.

**Comment by Flyer53** [comment]
And the next alpha update is available ...
https://alpha.jspanel.de/downloads/jspanel-4.5.0-alpha16.zip
`panel.getChildpanels()` now accepts a callback as parameter and returns a NodeList (instead of an array)
https://alpha.jspanel.de/api.html#methods/getChildpanels

**Comment by akstek** [comment]
> The Pointer Event API is only used when supported by the browser. Otherwise Touch and/or Mouse Event APIs are used.
Good to hear and thx for the new alpha

**Comment by Flyer53** [comment]
https://alpha.jspanel.de/downloads/jspanel-4.5.0-alpha26.zip

**Comment by Flyer53** [comment]
@akstek 
I just uploaded jsPanel[ v4.5.0-beta.1](https://beta.jspanel.de/downloads/jspanel-4.5.0-beta.1.zip) to https://beta.jspanel.de/

+ jsPanel now uses **pointer events** if supported
+ **bugfix** - recoded the complete `close()` function to fix a long standing bug
+ **bugfix** in `jsPanel.position()` concerning the use of the **dock extension**
+ **bugfix** in `minimize()` concerning the use of an image as background
+ **bugfix** in option `dragit`
+ **option theme** got numerous updates:
  + additional built-in themes
  + updated built-in theme colors
  + all built-in themes are are now "normal" color themes &rarr; less CSS
  + recoded bootstrap theme support &rarr; no more bootstrap adjustments in *jspanel.css* needed
  + option theme can now be used with an object as value &rarr; more theming options and better support of images (includes css gradients) as panel background
+ **added** option `onparentresize` to autoreposition childpanels on various resize actions of the parentpanel
+ **added** parameter `status` to the callbacks `onbeforemaximize`, `onmaximized` etc.
+ **added** parameter options `'hide'` and `'show'` to panel method `setControlStatus()` parameter `action`
+ **added** optional callback function to panel method `getChildpanels()` and the method now returns a NodeList (instead of an array)
+ **added** optional callback function to panel method `isChildpanel()`
+ **added** support for setting `option.position.of` in a **position shorthand string**
+ various minor fixes/improvements in js and css

**Comment by Flyer53** [comment]
@akstek 
I just released v4.5.0
I there anything more to say about this issue?
Otherwise I'd ask you to close it ...
