### ISSUE TITLE
[QUESTION] Layout Extension with dynamically created panels

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel4#66]
Hello,

I have a question about https://jspanel.de/api.html#extensions/layout.

The documentation states:

> 1. create an object with predefined panel configurations

How about panels that are created as a result of user's interaction with the system (random params like toolbar config, positioning, theme, etc)? Is there a jsPanel method that would "extract" current panel config and stick it into `predefinedConfigs`?

Also, each of my panels have `callback: function(panel) {}` callback. How should I treat that in `predefinedConfigs`?

Thanks!

**Comment by Flyer53** [comment]
Hi Temuri,

first something about the layout extension: The layout extension relies on `localStorage` to save data about size, position and status (maximized, minimized, etc.) of the panels, not more. It does not save anything else.

> Is there a jsPanel method that would "extract" current panel config and stick it into predefinedConfigs?

No.  You just have the property `options` that stores all options the panel was created with but it does not update during the lifetime of a panel (except all the arrays that take callback functions). So if you need to keep track of changes made during the lifetime of a panel, no matter whether the changes are made by the user or you, you would have to implement something yourself.

predefinedConfigs (`options.config`) is meant to store some panel configuration data that is shared by a number of panels. For example some hints that all have the same size, position, header config etc.
This could include option `callback` as well if the callback is the same for all the panels using that predefined config.

If you could tell me a bit more about your usecase/intentions I might be able to give better help ;)

Regards,
Stefan

**Comment by temuri416** [comment]
Thanks, Stefan.

I see what you're saying. You could answer all my questions by adding another example to the documentation that would do something like this:

1. Start off with: 
`var predefinedConfigs = {}`
2. Add a button "**CREATE PANELS**" that will open panel at random positions, of random sizes
3. Each spawned panel adds itself to `predefinedConfigs`.
4. Have "**SAVE LAYOUT**" button that'll memorize layout and will close all open panels.
5. Have "**RESTORE PANELS**" that'll reopen everything that "**SAVE LAYOUT**" closed.

That is really my usecase :-)

Thank you!

**Comment by Flyer53** [comment]
Ok,
I created a first example to start with. It creates 6 panels with random size and position, saves layout and restores panels.
Check out https://jspanel.de/docs/demos/randomPanels.html and tell me what else you need ... 😏

**Comment by temuri416** [comment]
Thanks, I'll review your example tomorrow and will get back to you!

**Comment by Flyer53** [comment]
Added a second example that actually uses the `predefinedConfig` object
[https://jspanel.de/docs/demos/randomPanels2.html](https://jspanel.de/docs/demos/randomPanels2.html)

**Comment by temuri416** [comment]
Hi Stefan,

Something is bothering me in your second example. Let me try to explain :-)

**First**, I notice is that `jsPanel.layout.save();` does not even care about `predefinedConfig`, which gets stuffed with configs from randomly created panels. That seems odd to me, especially that when restoring panels, you do:

        jsPanel.layout.restore({
            configs: predefinedConfigs
        });

So, why are not doing this?

        jsPanel.layout.save({
            configs: predefinedConfigs
        });

**Second**, let's say `predefinedConfigs` is populated with panels' positions and dimensions **AND** you're restoring with **{configs: predefinedConfigs}**. Then, if I repositon/resize one of the panels, I'd expect respective `predefinedConfigs[panelId]` to be updated accordingly and then being used to restore positions/sizes. But that does not happen either, as during restore you have this line:

    panelSize: { width: storedpanel.width, height: storedpanel.height },
    position: { my: 'left-top', at: 'left-top', offsetX: storedpanel.left, offsetY: storedpanel.top },

And `storedpanel` is coming from `localStorage`.

So, it's a bit unclear why `predefinedConfigs` is required at all, if you go to localStorage?

Hope my questions make sense :-)

Cheers!

**Comment by Flyer53** [comment]
Hi Temuri,

The only purpose of the layout extension so far is to restore position, size, status and z-index order of one or more panels (the id is also stored to identify the panel within the object containing the rest of the configuration). So it stores the data needed to accomplish this to localStorage in order to have this data available even if the user comes back later, but not more. The rest of the configuration has to come from somewhere else and this is the object I called predefinedConfig in this case.  **localStorage** stores only string values btw!
When you restore panels using the layout extension the panels position, size, status and z-index is always taken from the values stored in localStorage, no matter what values might be in a predefined config object. That's the purpose of the layout extension ... to restore panel position, size, status and z-index the user adjusted his panels to before he left the page.

Option `config` was initially intended only for usecases where you have common configuration options for  several panels. So you need to write them only once, and, if needed, can change them at only one place instead of within each panel configuration. It just happens to come in handy when you need to merge a panel config with the values stored by the layout extension.

Of course you could modify the layout extension to store more than just those few values. But as soon as it's necessary to store non-string values it gets a bit more complicated. I designed the layout extension on request of another user some time ago, and he didn't need more than position, size and status.

I hope this explains a bit ;)

**Comment by temuri416** [comment]
I see, thanks for the insight!

Hope those two examples will make it to the official documentation - they're really useful.

Cheers :-)
