### ISSUE TITLE
Error with Jspanel.close in certain situations in jspanel 4.5.0

### ISSUE THREAD

**Issue by AviHafner** [Flyer53/jsPanel4#71]
Hi Stefan
In version 4.50 in particular situations,
I am getting the error :
**TypeError: Cannot read property 'removeChild' of null**
**at Object.close**
**At HTMLDivElement.i.close**

To see the error ,Please use the example 
http://www.admin.technion.ac.il/avi/

How to produce the error
1)	press on the info button
2)	in the panel, press on the close button
3)	press on anther info button – and the error will be occurred

Yours 
Avi Hafner

**Comment by Flyer53** [comment]
@AviHafner 
Hi Avi,
that has to do with the note you can read in the docs of [.close()](https://jspanel.de/api.html#methods/close)

So I suggest you add
```javascript
onclosed: function() {
    panel = undefined;
}
```
to the panel configuration and it should work.

**Note:**
Further down in your code you have the following:
```javascript
p.footer.querySelector('#btn-close').addEventListener('click', function (e)
{
    e.stopPropagation();
    p.close();
    return false;
}, 'click');
```
`'click'` is not a valid third argument for `addEventListener`. See [developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)
I suggest you simply remove it.

Yours,
Stefan :)

**Comment by AviHafner** [comment]
Hi Stefan
1)	**onclosed:**
You know that what you wrote is a change in the behavior of the product   :**jsPanel**
2)	Despite what you wrote, it took me time to see the unnecessary click that you wrote about it.

Yours
Avi Hafner

**Comment by Flyer53** [comment]
Hi Avi,
I don't remember when I added this note to the docs, but the fact itself is not new.
And if that's an option for you it wouldn't be a problem to do your code without assigning the panel to a variable at all.

**Comment by AviHafner** [comment]
Thanks Stefan
It is always a pleasure to receive information and knowledge from you.

Yours
Avi

**Comment by AviHafner** [comment]
Hi Stephen
The problem that I’m raising (.close())  is a **bug at jsPanel**.
I'd rather get your patch to the bug and not go into all my programs and places the fix you're offering.

I want in the future to **adopt minor changes in versions of jsPanel smoothly**, without any changes to my code.


Yours always,
Avi Hafner

**Comment by Flyer53** [comment]
Hi Avi,
please take a look at your example at https://jspanel.de/docs/demos/avi/
I modified it a bit to do without assigning the panels to a variable. It works perfectly well without showing any errors.
If you think there is a bug then I ask you to explain it please. I don't see it.

**Notes on `.close()`**
The `close()` method only removes the HTML code of the panel from the DOM. It does not do anything with a variable you might have assigned the panel to. Not alone because I can't anticipate how you name variables. So if your panel is assigned to a variable this variable will remain in memory, even if the panel is closed, until you do something about that.
If you assign a panel to a variable you do that for a purpose. I can not know your specific purpose and I can not anticipate how you name your variable. When and how you work with this variable is completely up to you and I can't interfere with that.
I always try to work without assigning a panel to a variable.

Yours,
Stefan

PS: Tomorrow I'll leave for a trip to the mountains for about a week. So you won't hear anything from me the next days ... ;)

**Comment by AviHafner** [comment]
Thanks Stefan

The solution you sent me is new to me.
I understand that I can refer to the id="**MobileInfo**" object at any time,
And see if it exists, rather than checking the object I put the jsPanel into.

Stefan, 
when did you adopt this attitude, because this form of coding  is new to me

This is a slightly different reference to Jspanel and a perfect solution for me.

Stefan I green with envy ,and the reason is  yours trip tomorrow,
 and in my dreams I'm with you on the trip in mountain walks

yours
Hefner Avi

**Comment by Flyer53** [comment]
@AviHafner 
Well Avi, I'm not aware that I adopted a certain way for a specific reason. It's probably just the result of how I developed jsPanel and I don't even think it's something special.

Btw: https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild is a good read that gives some valuable information about what happens to a variable after removing the DOM element stored in it.

Youry,
Stefan

**Comment by AviHafner** [comment]
Hello Stefan

The first method that I tried, and it does not work in Firefox but in the rest of the browsers it works.
Is to put the CSS file name at the Head of HTML,
And make by code the file Disable or Enable.

The second method that works in all the browsers is to load and remove the CSS file dynamically .

Yours
Avi Hafner
