### ISSUE TITLE
Resize bug

### ISSUE THREAD

**Issue by hennymugge** [Flyer53/jsPanel4#72]
When resizing and moving the mouse fastly, the panel gets stuk in resize mode: after releasing the mouse, everytime the mouse hovers in, the panel starts resizing again and gets unusable. This is the case when used in a Chrome app and chrome extension. Both Mac an ChromeOS. Would be great if there was a fix for this 👍 

Edit: accidentally happens on dragging as well.
 
![zuzvv-thykg](https://user-images.githubusercontent.com/47762836/52982367-ff951b00-33e5-11e9-946d-f2ec0d784c8d.gif)

**Comment by Flyer53** [comment]
Can you tell me a little bit more?
+ do you use the latest jsPanel release 4.5.0?
+ do you get any error messages?
+ is it correct that your panel content is an iframe?
+ is the panel itself within an iframe?

So far I could observe this kind of issue only when iframes were involved in some kind and could fix it in environments I can test with. Since I don't have any Mac and/or Chrome OS devices I can't reproduce your issue.

**Note:** I can test jsPanel only in various browsers running on a Windows machine and on an iPad and some Android devices.

**Comment by hennymugge** [comment]
Hello Flyer53. Thank you for coming back at me!

I'm using 4.5.0.
There are no error messages in the console.
The content is a webview element (to my understanding, Chrome creates an iframe in a webview though).
The panel itself is hovering above the other webview. So it's not a child of _that_ webview, its a direct child of the body.

Pretty hard fixing a bug that you cannot test yourself! Maybe you could point me to where to look? :)

**Comment by Flyer53** [comment]
@hennymugge 
Ok, assuming a webview behaves like an iframe the solution seems to be easy. So I try to explain the issue using iframes.
The point is that the iframe the panel is hovering above is a completely different document. So the mouseup you do after quickly dragging/resizing the panel might occur over another document (the iframe) than the panel belongs to. But the document the panel belongs to never fired the mouseup -> handler is not unbound.

In a demo I solved this by setting the iframes css `pointer-events: 'none'` while dragging/resizing the panel.
Demo with an iframe: https://jspanel.de/docs/demos/panel_over_iframe.html

I don't know whether a webview is accessible the same way to set a css property and whether it supports css pointer-events at all. It's worth to try however.

Let me know whether this is of any help please.

Regards,
Stefan

**Comment by hennymugge** [comment]
You sir, are a legend! It's working absolutely briliant. Thank you so much!!!!!

**Comment by Flyer53** [comment]
My pleasure, glad I could help 😄
