### ISSUE TITLE
No support for multi-touch gestures

### ISSUE THREAD

**Issue by thehovercam** [Flyer53/jsPanel4#73]
Windows 10 touch screen, latest Chrome browser, latest jsPanel 4.5.0

1. Touch panel header with two fingers to try to drag, then drag feature will stop working, panel will move to any where finger or mouse is. The only thing we can do is reloading the page again. It happens on the demo page [https://jspanel.de/api.html](https://jspanel.de/api.html) as well (It supposes to be one finger drag move, but user may touch with two fingers some how).

2. use mouse to drag the panel to be snapped at bottom. then try to use finger to drag it out, it will trigger the bug as well, tested it here.
[https://jspanel.de/api.html#properties/snapped](https://jspanel.de/api.html#properties/snapped)

**Comment by Flyer53** [comment]
@thehovercam 
Thanks for the info.
Currently jsPanel supports single touch points at a time. But it doesn't support multi touch points.
I'll try to improve this issues but since I don't own a Windows device with touch screen my options are a bit limited.
I'll see what I can do with an Android device supporting touch and mouse. May be that helps ...

**Comment by Flyer53** [comment]
@thehovercam 
As already said, I don't have a Windows device supporting mouse AND touch.

1. I can reproduce your example 1 on an Android device.
2. I cannot reproduce example 2. Works as expected on Android.

As far as I see it there is nothing wrong with the touch functionallity. jsPanel simply doesn't support multi-touch gestures and I don't plan to change that.
