### ISSUE TITLE
Looses panel handle - out of container

### ISSUE THREAD

**Issue by itpmngt** [Flyer53/jsPanel4#8]
Noticed that we loose the handle of a panel if we drag them beyond the container. If we go to http://jspanel.de/docs/#methods/getChildpanels, click on Execute example and drag one of the children out of the container-panel we loos the panel behind other elements. Maybe some constrains to the dragit function?

It happens as well as when the container is the <body> or any other tag for the matter...

**Comment by itpmngt** [comment]
Chances are that relates to the 'axis' property of 'dragit' - is not respecting the boundaries
(using Chrome on MAC)

**Comment by Flyer53** [comment]
@itpmngt 
Those 2 "childpanels" are appended to the content section of "parentpanel". Since the css **overflow** property of a panels content section is set to hidden a childpanel won't be visible anymore if you drag it beyond the parent containers boundaries.

Depending on your needs I suggest that you use the **containment setting** of **[option.dragit](http://jspanel.de/docs/#options/dragit)** and/or **[option.resizeit](http://jspanel.de/docs/#options/resizeit)** or just set **[option.syncMargins](http://jspanel.de/docs/#options/syncMargins)** to **_true_**.

I changed the example to use option.syncMargins

**Comment by itpmngt** [comment]
Thanks Stefan - effective as always

Maybe it would be good to put the text above on that page and/or container - it explains containment succinctly (I think)

Best

**Comment by Flyer53** [comment]
My pleasure Joe,
There sure is some work to do concerning documentation. But it's not that bad already I think 😏 and I'll try to further improve it ...
Happy coding,
Stefan
