### ISSUE TITLE
[NFR] Window resize behaviour modifier keys

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel4#97]
Hello there!

I've two feature requests :-)

1. Holding ALT key when resizing using the four corners handles would lock window width/height ratio (i.e. resize will maintain current window proportions)
2. Holding CTRL key when resizing anywhere would mirror increase or decrease in size of the opposite border (i.e. if moving bottom frame border up, the upper border would move down by the same amount) - same should happen when dragging by corner handles.

Thank you!

**Comment by Flyer53** [comment]
Hi Temuri,
Thanks for the feedback.
I'll take a look at that proposal. But currently I'm on vacation for a few days.
So be patient please ...
Regards,
Stefan

**Comment by Flyer53** [comment]
@temuri416 
Hi Temuri,
the latest alpha from today has the following addition:
Regardless of which resize handle you use
+ holding the CTRL key while resizing maintains the aspect ratio of the panel dimensions as a whole, so that is the same as setting `aspectRatio: true`
+ holding the ALT key while resizing maintains the aspect ratio of the content section, so that is the same as setting `aspectRatio: 'content'`

Using the modifier keys **does not override** a setting of option.resizeit.aspectRatio

So that is a bit like your request No 1.
Your request No 2 is something different and I don't know yet whether I'll try to implement it ... would be a lot more complicated.

You may [download v4.8.0-alpha.5
](https://alpha.jspanel.de/downloads/jspanel-4.8.0-alpha.5.zip)
I would appreciate if you gave it a try and provide some feedback.

Regards,
Stefan

**Comment by temuri416** [comment]
I'll check it out on the weekend.

thanks!!!

**Comment by Flyer53** [comment]
@temuri416 
It's been four weeks since ... any time to take a look?

**Comment by temuri416** [comment]
ugggghhh I apologize. started a new job and suddenly had to work several weekends in a row.

I'll get to that asap :)

thank you :)

**Comment by Flyer53** [comment]
@temuri416 
There's no real hurry ... take your time. The new job is more important 😏

**Comment by Flyer53** [comment]
@temuri416 
Ok ... just uploaded a new 4.9.0 alpha version to https://alpha.jspanel.de/api.html#options/resizeit/modifier-keys with an update for the modifier key feature. Seems to work reasonably well now.
[Download v4.9.0-alpha.6](https://alpha.jspanel.de/downloads/jspanel-4.9.0-alpha.6.zip)

Whenever your time permits ...

**Comment by temuri416** [comment]
Hello,

I've just looked at it - ALT modifier does exactly what I had in mind 👍. 

However, it seems like I did not explain myself clearly what CTRL modifier should do. I thought it would be a good idea to mirror resize direction of the opposite window edge. That way you'll be growing or contracting window size twice as fast.

Say window's size is 500x500 px and while holding CTRL you start dragging right edge to the right of you by 100 px. Then, the left edge of the window will move to the left by the same amout. I.e. after you release mouse button, your window will be 700x500, instead of 600x500.

What do you think?

**Comment by Flyer53** [comment]
Oh I fully understood your request. But first I wanted to have both `aspectRatio` variants available via modifier keys.
And now I'm working on the feature you posted as No 2 in your original post. It will use the `Shift` key. I might have something later today ... if not, then next week. I'm away over the weekend.

**Comment by Flyer53** [comment]
Take a look at https://alpha.jspanel.de/api.html#options/resizeit and scroll down to the modifier keys description.
[Download updated v4.9.0-alpha.7](https://alpha.jspanel.de/downloads/jspanel-4.9.0-alpha.7.zip)
As said in the docs it does not work perfectly well in combination with some of the other resizeit parameters. But I don't consider this critical ...

**Comment by temuri416** [comment]
It works reasonably well, I think :-) thanks a lot!

**Comment by Flyer53** [comment]
Modifier keys implemented in v4.9.0 release
